Repository astropy/halotools, pull requests merged in 2019-05, with the labels that each got.

#931 Fix inconsistent return idx
  halotools/mock_observables/counts_in_cells/counts_in_cylinders.py
  halotools/mock_observables/counts_in_cells/engines/counts_in_cylinders_engine.pyx
  halotools/mock_observables/counts_in_cells/tests/test_counts_in_cylinders.py
Labels: bug-fix, empirical-models

#930 Update some docstrings + error messages
  halotools/empirical_models/factories/prebuilt_model_factory.py
  halotools/sim_manager/fake_sim.py
Labels: documentation

#925 fix bug in docstring of `wp_jackknife`
  halotools/mock_observables/two_point_clustering/wp_jackknife.py
Labels: bug, documentation
